n = str(input('Digite seu nome completo: ')).lower().strip()
nome = n.split()
print('seu nome é {}'.format(nome))
print('primeiro nome {}'.format(nome[0]))
print('Seu último nome é {}'.format(nome[len(nome)-1]))